/**
 * Theme defaults / apply / export — re-exported from `burne-ui`.
 * Requires burne-ui with Theme API (BurneUIProvider / applyThemeTokens).
 */
export {
  ANIMATION_FLAG_LABELS,
  BORDER_COLOR_CSS_FORMULA,
  BORDER_COLOR_CSS_FORMULA_BY_THEME,
  COLOR_CSS_VAR,
  COLOR_LABELS,
  DEFAULT_FONT,
  DEFAULT_FONT_MONO,
  FONT_PRESETS,
  FONT_WEIGHT_CSS_VAR,
  FONT_WEIGHT_DEFAULTS,
  FONT_WEIGHT_LABELS,
  GSAP_EASE_OPTIONS,
  LAYOUT_PRESETS,
  MONO_FONT_PRESETS,
  MOTION_DURATION_LABELS,
  MOTION_EASE_LABELS,
  MOTION_SCALE_LABELS,
  RIPPLE_EASE_CSS_OPTIONS,
  SCALE_DEFAULTS,
  SCALE_TOKEN_LABELS,
  STATUS_FOREGROUND_CSS_VAR,
  STATUS_FOREGROUND_LABELS,
  TEXT_SCALE_BASES,
  applyThemeTokens,
  clearThemeInlineTokens,
  createDefaultThemeState,
  exportThemeCss,
  isBorderColorCustomized,
  isDefaultBorderColor,
  type ColorPresetKey,
  type LayoutPresetKey,
  type ThemeColorKey,
  type ThemeColors,
  type ThemeFontWeightKey,
  type ThemeFontWeights,
  type ThemeMode,
  type ThemeStatusForegroundKey,
  type ThemeStatusForegrounds,
  type ThemeTokenState,
} from "burne-ui";
